apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: staging
spec:
  interval: 5m
  chart:
    spec:
      chart: ../../wordp
      version: "18.x.x"
      valuesFiles:
        - ../../wordp/values-prod.yaml
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

