apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb-operator
      version: "0.29.x"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  values:
    webhook:
      enabled: true
