apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: production
spec:
  interval: 15m
  timeout: 5m
  targetNamespace: production
  chart:
    spec:
      chart: ../../wordp
      version: "18.x.x"
      valuesFiles:
        - ../../wordp/values-prod.yaml
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system


